import { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
  return knex.schema
    .alterTable("access_codes", table => {
      table.dropNullable("user_id")
      table.dropNullable("selector")
      table.dropNullable("validator")
      table.dropNullable("created_at")
      table.dropNullable("expires_at")
      table.dropNullable("user_agent")
      table.dropNullable("ip")
      table.dropNullable("service")
    })
    .alterTable("access_tokens", table => {
      table.dropNullable("user_id")
      table.dropNullable("selector")
      table.dropNullable("validator")
      table.dropNullable("created_at")
      table.dropNullable("expires_at")
      table.dropNullable("user_agent")
      table.dropNullable("ip")
      table.dropNullable("service")
    })
    .alterTable("email_change_password", table => {
      table.dropNullable("user_id")
      table.dropNullable("selector")
      table.dropNullable("validator")
      table.dropNullable("issued_at")
      table.dropNullable("sent_at")
      table.dropNullable("expires_at")
    })
    .alterTable("email_confirm_email", table => {
      table.dropNullable("user_id")
      table.dropNullable("email")
      table.dropNullable("selector")
      table.dropNullable("validator")
      table.dropNullable("issued_at")
      table.dropNullable("sent_at")
      table.dropNullable("expires_at")
    })
    .alterTable("email_confirm_signup", table => {
      table.dropNullable("username")
      table.dropNullable("email")
      table.dropNullable("selector")
      table.dropNullable("validator")
      table.dropNullable("issued_at")
      table.dropNullable("sent_at")
      table.dropNullable("expires_at")
    })
    .alterTable("email_revert_email", table => {
      table.dropNullable("user_id")
      table.dropNullable("email")
      table.dropNullable("selector")
      table.dropNullable("validator")
      table.dropNullable("issued_at")
      table.dropNullable("sent_at")
      table.dropNullable("expires_at")
    })
    .alterTable("email_verify_login", table => {
      table.dropNullable("user_id")
      table.dropNullable("selector")
      table.dropNullable("validator")
      table.dropNullable("issued_at")
      table.dropNullable("sent_at")
      table.dropNullable("expires_at")
      table.dropNullable("verified")
      table.dropNullable("ip")
    })
}

export async function down(knex: Knex): Promise<void> {
  return knex.schema
    .alterTable("access_codes", table => {
      table.setNullable("user_id")
      table.setNullable("selector")
      table.setNullable("validator")
      table.setNullable("created_at")
      table.setNullable("expires_at")
      table.setNullable("user_agent")
      table.setNullable("ip")
      table.setNullable("service")
    })
    .alterTable("access_tokens", table => {
      table.setNullable("user_id")
      table.setNullable("selector")
      table.setNullable("validator")
      table.setNullable("created_at")
      table.setNullable("expires_at")
      table.setNullable("user_agent")
      table.setNullable("ip")
      table.setNullable("service")
    })
    .alterTable("email_change_password", table => {
      table.setNullable("user_id")
      table.setNullable("selector")
      table.setNullable("validator")
      table.setNullable("issued_at")
      table.setNullable("sent_at")
      table.setNullable("expires_at")
    })
    .alterTable("email_confirm_email", table => {
      table.setNullable("user_id")
      table.setNullable("email")
      table.setNullable("selector")
      table.setNullable("validator")
      table.setNullable("issued_at")
      table.setNullable("sent_at")
      table.setNullable("expires_at")
    })
    .alterTable("email_confirm_signup", table => {
      table.setNullable("username")
      table.setNullable("email")
      table.setNullable("selector")
      table.setNullable("validator")
      table.setNullable("issued_at")
      table.setNullable("sent_at")
      table.setNullable("expires_at")
    })
    .alterTable("email_revert_email", table => {
      table.setNullable("user_id")
      table.setNullable("email")
      table.setNullable("selector")
      table.setNullable("validator")
      table.setNullable("issued_at")
      table.setNullable("sent_at")
      table.setNullable("expires_at")
    })
    .alterTable("email_verify_login", table => {
      table.setNullable("user_id")
      table.setNullable("selector")
      table.setNullable("validator")
      table.setNullable("issued_at")
      table.setNullable("sent_at")
      table.setNullable("expires_at")
      table.setNullable("verified")
      table.setNullable("ip")
    })
}