export const Block = {
  CallToAction: (label: string, link: string) =>
    `<table role="presentation" border="0" cellpadding="0" cellspacing="0" class="btn btn-primary"><tbody><tr><td align="left"><table role="presentation" border="0" cellpadding="0" cellspacing="0"><tbody><tr><td><center><a href="${link}" target="_blank">${label}</a></center></td></tr></tbody></table></td></tr></tbody></table>`,
  Text: (text: string) => `<p>${text}</p>`,
  Subtitle: (text: string) => `<h2>${text}</h2>`,
  Title: (text: string) => `<h1>${text}</h1>`,
  Link: (label: string, link: string) =>
    `<p><a href="${link}">${label}</a></p>`,
  Card: (html: string) =>
    `<table role="presentation" class="main" style="border-collapse:separate;mso-table-lspace:0;mso-table-rspace:0;background:#fff;border-radius:16px;width:100%" width="100%"><tr><td class="wrapper" style="font-family:sans-serif;font-size:14px;vertical-align:top;box-sizing:border-box;padding:20px" valign="top"><table role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;mso-table-lspace:0;mso-table-rspace:0;width:100%" width="100%"><tr><td style="font-family:sans-serif;font-size:14px;vertical-align:top" valign="top">${html}</td></tr></table></td></tr></table>`,
  Document: (title: string, description: string, html: string) =>
    `<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><title>${title}</title><style>@media only screen and (max-width:620px){table.body h1{font-size:28px!important;margin-bottom:10px!important}table.body a,table.body ol,table.body p,table.body span,table.body td,table.body ul{font-size:16px!important}table.body .article,table.body .wrapper{padding:10px!important}table.body .content{padding:0!important}table.body .container{padding:0!important;width:100%!important}table.body .main{border-left-width:0!important;border-radius:0!important;border-right-width:0!important}table.body .btn table{width:100%!important}table.body .btn a{width:100%!important}table.body .img-responsive{height:auto!important;max-width:100%!important;width:auto!important}}@media all{.ExternalClass{width:100%}.ExternalClass,.ExternalClass div,.ExternalClass font,.ExternalClass p,.ExternalClass span,.ExternalClass td{line-height:100%}.apple-link a{color:inherit!important;font-family:inherit!important;font-size:inherit!important;font-weight:inherit!important;line-height:inherit!important;text-decoration:none!important}#MessageViewBody a{color:inherit;text-decoration:none;font-size:inherit;font-family:inherit;font-weight:inherit;line-height:inherit}}</style></head><body style="background-color:#f6f6f6;font-family:sans-serif;-webkit-font-smoothing:antialiased;font-size:14px;line-height:1.4;margin:0;padding:0;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%;min-height:100vh"><span class="preheader" style="color:transparent;display:none;height:0;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;visibility:hidden;width:0">${description}</span><table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body" style="border-collapse:separate;mso-table-lspace:0;mso-table-rspace:0;background-color:#ebedee;width:100%" width="100%" bgcolor="hsl(200, 10%, 93%)"><tr><td class="container" style="font-family:sans-serif;font-size:14px;vertical-align:top;display:block;max-width:580px;padding:10px;width:580px;margin:0 auto" width="580" valign="top"><div class="content" style="box-sizing:border-box;display:block;margin:0 auto;max-width:580px;padding:10px">${html}</div></td></tr></table></body></html>`,
  Logo: (image: string, altText: string) =>
    `<div align="center"><center><img src="${image}" alt="${altText}" style="display:block;width:120px;height:auto;margin:10px auto 20px"></center></div>`,
  Footer: () =>
    `<div class="footer" style="clear:both;margin-top:10px;text-align:center;width:100%"><table role="presentation" border="0" cellpadding="0" cellspacing="0" style="border-collapse:separate;mso-table-lspace:0;mso-table-rspace:0;width:100%" width="100%"><tr><td class="content-block" style="font-family:sans-serif;vertical-align:top;padding-top:10px;color:#899ea8;font-size:12px;text-align:center;padding-bottom:30px" valign="top" align="center"><span class="apple-link" style="color:#899ea8;text-align:center;font-size:16px">&copy;&nbsp;2023&nbsp;<b>Dorkodu</b></span></td></tr></table></div>`,
  ValuePairs: (pairs: Array<[string, string]>) =>
    `<p><table>${pairs.map(
      ([k, v]) => `<tr><td><b><u>${k}</u>:</b></td><td>${v}</td></tr>`
    )}</table></p>`,
  Divider: () => `<hr/>`,
};
