POST http://localhost:8888/api/auth/login?redirect_uri=localhost HTTP/1.1
Content-Type: application/json

{
  "usernameOrEmail": "a@a.com",
  "password": "12345678"
}

###

POST http://localhost:8888/api/auth/signup?redirect_uri=localhost HTTP/1.1
Content-Type: application/json

{
  "username": "aaaaaa",
  "email": "aaaaaa@a.com",
  "password": "12345678"
}

###

POST http://localhost:8888/api/auth/logout HTTP/1.1
Content-Type: application/json

{
  "token": "FYwIcfIEcJUJMYEdyoQhJQ:_joZniIp8IVtBHfDuHIrLxuvj_3dhPQu0tRx6-fLpq8"
}

###

POST http://localhost:8888/api/auth/temporaryAuth HTTP/1.1
Content-Type: application/json

{
  "token": "JcQKD6cI5iAjcxx55lAvOiovamO2TnSMasN2co7IKnQ"
}

###

POST http://localhost:8888/api/auth/auth HTTP/1.1
Content-Type: application/json

{
  "token": "FYwIcfIEcJUJMYEdyoQhJQ:_joZniIp8IVtBHfDuHIrLxuvj_3dhPQu0tRx6-fLpq8"
}

###

POST http://localhost:8888/api/auth/refreshAuth HTTP/1.1
Content-Type: application/json

{
  "token": "1ApuS3NIUvBsahGYFu1f_g:ffnVXZsoXhTkhhP3WfM9wi-h7ykAd7ckcWtosnY9lE0"
}

###