FROM node:16.17.1-alpine
WORKDIR /id/next

RUN npm install -g pnpm && pnpm config set --global store-dir /root/.local/share/pnpm/store/v3

COPY ./next/pnpm-lock.yaml /id/next
RUN pnpm fetch
COPY ./next /id/next
RUN pnpm install --offline

#RUN pnpm test
RUN pnpm build