POST http://localhost:8888/api HTTP/1.1
Content-Type: application/json

{
  "type": "signup",
  "data": {
    "email": "krebbbbbbbb@kreb.com",
    "password": "1234567890"
  }
}

###

POST http://localhost:8888/api HTTP/1.1
Content-Type: application/json

{
  "type": "token",
  "data": {
    "token": "w6jCqmjDi1FPZcOkwpZ8c1LDq8Kla1I-bMOYSCUwwpXCiGHDn8OCw6bCl8OTM1U",
    "clientId": "a",
    "clientSecret": "a"
  }
}