FROM node:16.17.1-alpine
WORKDIR /id

RUN mkdir -p /id/api

RUN npm install -g pnpm && pnpm config set --global store-dir /root/.local/share/pnpm/store/v3

COPY ./api/pnpm-lock.yaml /id/api
RUN cd api && pnpm fetch
COPY ./api /id/api
RUN cd api && pnpm install --offline

WORKDIR /id/api
CMD [ "pnpm", "run", "dev" ]