FROM node:16.17.1-alpine
WORKDIR /id

RUN mkdir -p /id/web
RUN mkdir -p /id/api

RUN npm install -g pnpm && pnpm config set --global store-dir /root/.local/share/pnpm/store/v3

COPY ./web /id/web
COPY ./api /id/api
RUN cd /id/web && pnpm install && cd /id/api && pnpm install

WORKDIR /id/web
CMD [ "pnpm", "run", "dev" ]