FROM node:16.17.1-alpine as base
WORKDIR /id

RUN mkdir -p /id/web
RUN mkdir -p /id/shared

RUN npm install -g pnpm

WORKDIR /id/web

COPY ./web/pnpm-lock.yaml /id/web
RUN pnpm fetch
COPY ./web /id/web
COPY ./shared /id/shared
RUN pnpm install --offline

#RUN pnpm test
RUN pnpm build

FROM nginx:1.23.2-alpine
COPY --from=base /id/web/dist /etc/nginx/html
COPY ../nginx/nginx.conf /etc/nginx/conf.d