FROM node:16-alpine
WORKDIR /id

RUN mkdir -p /id/web
RUN mkdir -p /id/shared

RUN npm install -g pnpm

COPY ./web/pnpm-lock.yaml /id/web
RUN cd web && pnpm fetch
COPY ./web /id/web
COPY ./shared /id/shared
RUN cd web && pnpm install --offline

WORKDIR /id/web
CMD [ "pnpm", "run", "dev" ]